'use client'
import { Box, TextField, useTheme } from '@mui/material'
import Head from 'next/head'
import { useSettings } from 'src/hooks/useSettings'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'

export default function Home() {
  const theme = useTheme()
  const { settings } = useSettings()

  return (
    <>
      <Head>
        <title>Shoppy Pick | 2024 </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </>
  )
}

Home.getLayout = (page: React.ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
