import { NextPage } from 'next'
import Head from 'next/head'
import { ReactNode } from 'react'
import LayoutNotApp from 'src/views/layouts/LayoutNotApp'
import MyProfilePage from 'src/views/pages/my-profile'

type TProps = {}

const MyProfile: NextPage<TProps> = () => {
  return (
    <>
      <Head>
        <title>Shoppy Pick | 2024 </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MyProfilePage />
    </>
  )
}

export default MyProfile
MyProfile.getLayout = (page:  ReactNode) => <LayoutNotApp>{page}</LayoutNotApp>
