import { NextPage } from 'next'
import Head from 'next/head'
import BlankLayout from 'src/views/layouts/BlankLayout'
import RegisterPage from 'src/views/pages/register'

type TProps = {}

const MyProfile: NextPage<TProps> = () => {
  return (
    <>
      <Head>
        <title>Shoppy Pick | 2024 </title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <RegisterPage />
    </>
  )
}

export default MyProfile
